plated=yes
customno=no

env=uat

stg.ip=172.16.25.23
stg.port=1521
stg.dbname=DEVDB02
stg.bdusername=SASO_MVPI2
stg.dbpassword=samvpinew

uat.ip=172.16.25.23
uat.port=1521
uat.dbname=DEVDB02
uat.bdusername=SASO_MVPI
uat.dbpassword=saso_mvpi

previousattempt=1
inspectionresult=2
numberofpreviousdays=100
